### PR TITLE
New website

### PR DESCRIPTION
**Pull request by GeorgeGkas**
This pull request introduces a new website to be used as API reference for the project. A preview can be found on [https://georgegkas.github.io/stream.js-website](https://georgegkas.github.io/stream.js-website). 

[docpress](https://github.com/docpress/docpress) is used as documentation website generator. It's flexible nature allow us to create pages based on Markdown files, thus making the project more maintainable for the future collaborators. 

We exclude the following methods from the API Reference as it turns out to be internal mechanisms used by the library. If you think we need to include them, please provide a brief description of each one -I had a difficult time to understand how to document that methods-.

**Instance methods**
- Stream.prototype.toString()

**Static methods**
- Stream.continually()
- Stream.continuallyEager()
- Stream.iterateEager()

Finally, we add the project to Travis CI that handles the building and updating process automatically. In other words, if we need to update the documentation website in the future, we only have to write to `docs` folder. Travis CI will generate the build and update the `gh-pages` branch automatically. Right now Travis CI looks only in `georgegkas/new-website` branch for changes. When this pull request will be merged, we still have to transfer the ownership to the default `master` branch in `dionyziz/stream.js-website`.

This pull request is intended to close issues: #4 and #5

### CODE REVIEW

**Comment by GeorgeGkas** [comment]
@dotnetCarpenter @dionyziz I would like to see your reactions to this update.

**Comment by dionyziz** [comment]
I really like this restructuring. Let's go forward with this! Can we see a screenshot before it goes up?

**Comment by GeorgeGkas** [comment]
@dionyziz check it on my fork: [https://georgegkas.github.io/stream.js-website/](https://georgegkas.github.io/stream.js-website/)

**Comment by dionyziz** [comment]
Looks great overall! Can you check it on mobile? Some long sections are covered by the footer and the last line of text is not readable.

**Comment by GeorgeGkas** [comment]
Unfortunately, docpress does not fully support mobile screens yet. This is not something we can fix in our codebase as it depends on docpress core itself. But I do not see the reason why this should be a problem though. Most of the developers use a desktop computer, except when they are on the buss and want to check the API on their mobile, haha. But yet this is not something to consider ourselves with. If this is not the case, we can move to a more stable tool like gitbook.

**Comment by dionyziz** [comment]
Can we just add some padding to the bottom of every page (via a few blank lines)? This should address the issue.

**Comment by GeorgeGkas** [comment]
Unfortunately, this does not solve the issue. I'll open a new issue on docpress to get some feedback. Would you like to merge this pull request anyway?

**Comment by GeorgeGkas** [comment]
@dionyziz I just found the issue on their codebase. I'll propose a fix today. :)

**Comment by dionyziz** [comment]
LGTM

**Comment by GeorgeGkas** [comment]
The fix was accepted in docpress repo. We just have to wait until they update the npm package. Let me merge this pull request and open a new issue to remind us that we have to update the website when the new version of docpress comes out.

**Pull request merged**
